version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://localhost
      NEXT_PUBLIC_USER_SERVICE_URL: http://user-service:3001
      NEXT_PUBLIC_CONTENT_SERVICE_URL: http://content-service:3002
      NEXT_PUBLIC_MEDIA_SERVICE_URL: http://localhost:3003
      NEXT_PUBLIC_CATEGORY_SERVICE_URL: http://category-service:3004
      NEXT_PUBLIC_COMMENT_SERVICE_URL: http://localhost:3005
      NEXT_PUBLIC_ASGARDEO_REDIRECT_URL: http://localhost:3000
    depends_on:
      - user-service
    networks:
      - cms-network
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./next.config.js:/app/next.config.js
      - ./jest.config.js:/app/jest.config.js
      - ./jest.setup.js:/app/jest.setup.js
      - ./next-env.d.ts:/app/next-env.d.ts
      - frontend-node-modules:/app/node_modules
      - frontend-next:/app/.next

volumes:
  frontend-node-modules:
  frontend-next:
